# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.cache/wt} [current_project]
set_property parent.project_path {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/Sinus_creater.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/harmonic_adder.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/instrument_notes.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/sinus_clock.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/Top.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/VGA_TOP.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/PLAY_MODULE.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/SYNC.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/RGB_SELECT.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/DEFAULT_SONG_PLAYER.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/MAIN_MENU.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/SCREEN_SEL_FSM.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/Instrument_TOP.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/sawtooth_wave_generator.vhd}
  {D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/sources_1/new/Sawtooth_adder.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/constrs_1/new/MUSIC_TOP_CONST.xdc}}
set_property used_in_implementation false [get_files {{D:/OLD Desktops/Desktop Karadere/Vivado Projects/Term_Project/Term_Project.srcs/constrs_1/new/MUSIC_TOP_CONST.xdc}}]


synth_design -top Top_music -part xc7a35tcpg236-1 -flatten_hierarchy none


write_checkpoint -force -noxdef Top_music.dcp

catch { report_utilization -file Top_music_utilization_synth.rpt -pb Top_music_utilization_synth.pb }
